name: vvp_app
description: Vastu Virtual Planner - An app for Vastu-based home evaluations and recommendations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  # Firebase Core
  firebase_core: ^2.25.4
  # Firebase Authentication
  firebase_auth: ^4.17.4
  # Google Sign-in (optional)
  google_sign_in: ^6.2.1
  # Provider for state management (recommended)
  provider: ^6.1.1
  flutter_native_splash: ^2.3.10
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sensors_plus: ^3.0.2
  geolocator: ^10.0.1
  shared_preferences: ^2.2.0
  flutter_compass: ^0.8.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  intl: ^0.18.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
flutter_native_splash:
  # Background color
  color: "#FFFFFF"
  # Or use a background image
  # background_image: "assets/images/splash_background.png"
  
  # Logo to display
  image: "assets/images/logo.png"
  
  # For branding text under the logo
  # branding: assets/branding.png
  
  # Platform-specific options
  android: true
  ios: true
  
  # Full screen mode (hides status bar)
  fullscreen: true