//
//  AppConstants.swift
//  EkVastuAppIos
//
//  Created by Venkata Avula  on 9/5/25.
//

import Foundation

let  TEST_ACCESS_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1ZGF5YmFkaGUyNit2YmNoYmpAZ21haWwuY29tIiwibGFzdE5hbWUiOiJuYm5kaSIsInJvbGVzIjpbIlJPTEVfU1RVREVOVCJdLCJpc3MiOiJjNWE1NTkwNmNjMjQ0ZjQ4MzIyNmUwMmJjZmYyYjVmIiwidHlwZSI6InJlZnJlc2giLCJvcmdJZCI6Im1hcmtzYW1wbGV0ZXN0IiwidGlkIjoiOXhQMHA0ODB6UiIsIm1hc3RlcklkIjotMSwibmFtZSI6InRoZ3J1aWh0cnUiLCJpc05ld0NsaWVudCI6dHJ1ZSwibWFzdGVyT3JnSWQiOiJudWxsIiwiZXhwIjoxNzc1NDM2NjA0LCJpYXQiOjE3NTcwNDA2MDQsImVtYWlsIjoidWRheWJhZGhlMjYrdmJjaGJqQGdtYWlsLmNvbSIsImNpZCI6ImVaZDg5bmVSR1AifQ.pRZLVN1UdwYdIu44QApt6xVavKUuPvKJZXQSCh5y5F0"
